# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/verilog/Basys-3-Master.xdc

# IP: ip/xadc_wiz_10/xadc_wiz_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_10 || ORIG_REF_NAME==xadc_wiz_10} -quiet] -quiet

# XDC: ip/xadc_wiz_10/xadc_wiz_10_ooc.xdc

# XDC: ip/xadc_wiz_10/xadc_wiz_10.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_10 || ORIG_REF_NAME==xadc_wiz_10} -quiet] {/inst } ]/inst ] -quiet] -quiet
