# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.cache/wt [current_project]
set_property parent.project_path C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/user/AppData/Roaming/Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/new/clock_library.v
  C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/new/controler.v
  C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/new/exam01_combinational_logic.v
  C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/new/exam02_sequential_logic.v
  C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/new/top_module_of_smart_farm.v
}
read_ip -quiet C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/ip/xadc_wiz_2/xadc_wiz_2.xci
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/ip/xadc_wiz_2/xadc_wiz_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/ip/xadc_wiz_2/xadc_wiz_2.xdc]

read_ip -quiet c:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/ip/xadc_wiz_3/xadc_wiz_3.xci
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/ip/xadc_wiz_3/xadc_wiz_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/sources_1/ip/xadc_wiz_3/xadc_wiz_3.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/constrs_1/imports/verilog/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/user/Documents/GitHub/smartfarm/basys3_soc/basys3_soc.srcs/constrs_1/imports/verilog/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_module_of_smart_farm -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module_of_smart_farm.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_of_smart_farm_utilization_synth.rpt -pb top_module_of_smart_farm_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
